GET http://localhost:3000

###

GET http://localhost:3000/api/student

###

POST http://localhost:3000/api/student
Content-Type: application/json

{
    "first_name": "Ritik",
    "last_name": "S",
    "email": "rs@y.com"
}

###

DELETE http://localhost:3000/api/student/14


